### ISSUE TITLE
List of index & columns for a particular table?

### ISSUE THREAD

**Issue by fogoat** [boyddensmore/Maximo-Oracle-SQL-Public#1]
Hi, I'm trying to find a query that lists all the maximo indexes, the table, columns, etc. I'm trying to optimize a query between ASSET and WORKORDER.

**Comment by boyddensmore** [comment]
Hello, thanks for the question!  I just put together a query for this, let me know how it works for you.

[Maximo-Oracle-SQL-Public/DatabaseConfiguration/Object Indexes with Columns.sql](https://github.com/boyddensmore/Maximo-Oracle-SQL-Public/blob/master/DatabaseConfiguration/Object%20Indexes%20with%20Columns.sql)

**Comment by fogoat** [comment]
Thanks for the query. 

I'm trying to see if there is a way to produce a list that tells me how to join asset and workorder table efficiently so that queries run fast. Is there a way to know which fields in each table would join best? For example, workorder.assetnum and asset.assetnum needs to be joined. What other fields do I need to include in my join?  I know Maximo records SAMEAS information which helps to indicate which attributes in other objects match. Still, the data relationship between workorder.assetnum and asset.assetnum is not shown in SAMEAS. The Relationships tab shows some hints that may help with efficient joins...

![image](https://user-images.githubusercontent.com/6989799/37474688-35b6a826-282e-11e8-8daa-fb07e8177eae.png)

![image](https://user-images.githubusercontent.com/6989799/37475038-fc049754-282e-11e8-9b8d-7d391d88df6e.png)
