### ISSUE TITLE
Is there a Maximo Inventory subselect to get sum of curbal?

### ISSUE THREAD

**Issue by fogoat** [boyddensmore/Maximo-Oracle-SQL-Public#2]
I turned on SQL logging (INFO) in Maximo.

When in the Inventory module, it looks like the invbalances table is queried separately:

`(INVBALANCES) : select sum(curbal) from invbalances  where itemnum =  'blue_widget`

Is there a where clause I could put in Maximo's Inventory module to check for inventory itemnum less than qty 10?

**Comment by fogoat** [comment]
`exists (select itemnum from invbalances where itemnum = inventory.itemnum and curbal < 10)`

**Comment by boyddensmore** [comment]
You're too quick for me! :)
